services:
  - type: web
    name: safe-video-downloader
    env: node
    plan: free
    buildCommand: "npm install && pip install yt-dlp"
    startCommand: "node src/server.js"
    healthCheckPath: "/"
    envVars:
      - key: PORT
        value: 3000
      - key: YTDLP_PATH
        value: "/opt/render/projectshome/.local/bin/yt-dlp"
      - key: PYTHON_PATH
        value: "/usr/local/bin/python3"
